### ISSUE TITLE
Error in rule run_salmon_fq

### ISSUE THREAD

**Issue by h20gg702** [hyunhwan-bcm/SalmonTE#74]
Hi, I am trying to use `SalmonTE.py quant --reference=hs example`, but I faced a problem like below. Could you suggest a solution? I tried `brew install tbb `, but I still have.
`SalmonTE.py quant --reference=hs example
2023-05-09 19:37:29,530 Starting quantification mode
2023-05-09 19:37:29,530 Collecting FASTQ files...
2023-05-09 19:37:29,530 SalmonTE assumes that 'example' is a directory, and SalmonTE will search any FASTQ file in the directory.
2023-05-09 19:37:29,539 The input dataset is considered as a paired-ends dataset.
2023-05-09 19:37:29,540 Collected 4 FASTQ files.
2023-05-09 19:37:29,540 Quantification has been finished.
2023-05-09 19:37:29,540 Running Salmon using Snakemake
Building DAG of jobs...
2023-05-09 19:37:30,474 Building DAG of jobs...
Using shell: /bin/bash
2023-05-09 19:37:30,514 Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
2023-05-09 19:37:30,514 Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
2023-05-09 19:37:30,514 Rules claiming more threads will be scaled down.
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              4              1              1
total                      7              1              1

2023-05-09 19:37:30,521 Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              4              1              1
total                      7              1              1

Select jobs to execute...
2023-05-09 19:37:30,521 Select jobs to execute...
/bin/bash: line 1: 12314 Abort trap: 6           /Users/yoshiakisato/SalmonTE/salmon/darwin/bin/salmon quant -q -i /Users/yoshiakisato/SalmonTE/reference/hs -l A -1 /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R1.fastq -2 /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R2.fastq -o /Users/yoshiakisato/SalmonTE/SalmonTE_output/CTRL_2 -p 4 2> /dev/null
[Tue May  9 19:37:30 2023]
2023-05-09 19:37:30,745 [Tue May  9 19:37:30 2023]
Error in rule run_salmon_fq:
    jobid: 4
    input: /Users/yoshiakisato/SalmonTE/reference/hs, /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R1.fastq, /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R2.fastq
    output: /Users/yoshiakisato/SalmonTE/SalmonTE_output/CTRL_2
    shell:
        /Users/yoshiakisato/SalmonTE/salmon/darwin/bin/salmon quant -q -i /Users/yoshiakisato/SalmonTE/reference/hs -l A -1 /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R1.fastq -2 /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R2.fastq -o /Users/yoshiakisato/SalmonTE/SalmonTE_output/CTRL_2 -p 4 2>/dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

2023-05-09 19:37:30,745 Error in rule run_salmon_fq:
    jobid: 4
    input: /Users/yoshiakisato/SalmonTE/reference/hs, /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R1.fastq, /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R2.fastq
    output: /Users/yoshiakisato/SalmonTE/SalmonTE_output/CTRL_2
    shell:
        /Users/yoshiakisato/SalmonTE/salmon/darwin/bin/salmon quant -q -i /Users/yoshiakisato/SalmonTE/reference/hs -l A -1 /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R1.fastq -2 /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpekehwfec/CTRL_2_R2.fastq -o /Users/yoshiakisato/SalmonTE/SalmonTE_output/CTRL_2 -p 4 2>/dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
2023-05-09 19:37:30,746 Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
2023-05-09 19:37:30,747 Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-05-09T193729.706500.snakemake.log
2023-05-09 19:37:30,747 Complete log: .snakemake/log/2023-05-09T193729.706500.snakemake.log
Traceback (most recent call last):
  File "/Users/yoshiakisato/SalmonTE/SalmonTE.py", line 293, in <module>
    run(args)
  File "/Users/yoshiakisato/SalmonTE/SalmonTE.py", line 244, in run
    run_salmon(param)
  File "/Users/yoshiakisato/SalmonTE/SalmonTE.py", line 157, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yoshiakisato/SalmonTE/SalmonTE_output/EXPR.csv'`

**Comment by hyunhwan-jeong** [comment]
Hi @h20gg702, I guess it is related to #75, and could you tell me that what version of snakemake you are using?

**Comment by h20gg702** [comment]
Dear hyunhwan-jeong, 
```
snakemake --version
7.25.3
```
Thanks.

**Comment by h20gg702** [comment]
Hi hyunhwan-jeong, when I used the command appeared in error message like following `./salmon/darwin/bin/salmon quant -q -i reference/hs -l A -1 /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpr25su1_l/CTRL_2_R1.fastq -2 /var/folders/pv/zvpnvfk901qdw74sqzy8vg7r0000gn/T/tmpr25su1_l/CTRL_2_R2.fastq -o /Users/yoshiakisato/SalmonTE/SalmonTE_output/CTRL_2`, I got this message. `Version Info: ### PLEASE UPGRADE SALMON ###
### A newer version of salmon with important bug fixes and improvements is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
Sign up for the salmon mailing list to hear about new versions, features and updates at:
https://oceangenomics.com/subscribe
###` and I got CTRL_2 folder in Salmon_output directory. So I repeated using the salmon quant for CTRL_1, TARDBP_1, and TARDBP_2 like CTRL_2, and finally I got following message after ./SalmonTE.py quant --reference=hs example
`2023-07-20 13:12:32,712 Starting quantification mode
2023-07-20 13:12:32,712 Collecting FASTQ files...
2023-07-20 13:12:32,712 SalmonTE assumes that 'example' is a directory, and SalmonTE will search any FASTQ file in the directory.
2023-07-20 13:12:32,721 The input dataset is considered as a paired-ends dataset.
2023-07-20 13:12:32,721 Collected 4 FASTQ files.
2023-07-20 13:12:32,721 Quantification has been finished.
2023-07-20 13:12:32,721 Running Salmon using Snakemake
Building DAG of jobs...
2023-07-20 13:12:33,511 Building DAG of jobs...
Using shell: /bin/bash
2023-07-20 13:12:33,547 Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
2023-07-20 13:12:33,547 Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
2023-07-20 13:12:33,547 Rules claiming more threads will be scaled down.
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
total                      3              1              1

2023-07-20 13:12:33,553 Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
total                      3              1              1

Select jobs to execute...
2023-07-20 13:12:33,553 Select jobs to execute...
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...
Select jobs to execute...
2023-07-20 13:12:34,993 Select jobs to execute...
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...
Select jobs to execute...
2023-07-20 13:12:36,078 Select jobs to execute...
Complete log: .snakemake/log/2023-07-20T131232.940840.snakemake.log
2023-07-20 13:12:36,079 Complete log: .snakemake/log/2023-07-20T131232.940840.snakemake.log`
and in SalmonTE_output directory, EXPR.csv, MAPPING_INFO.csv, clades.csv, condition.csv files are appeared. but salmon_quant.log has empty contents. Does this result of salmon quant has anything wrong?
