### ISSUE TITLE
Snakemake problem

### ISSUE THREAD

**Issue by Walda007** [hyunhwan-bcm/SalmonTE#82]
Hi, thank you for this great tool, however I keep getting an error with snakemake. Is it a problem with the version? - 8.20.5? Which version is compatible?

2024-09-29 14:01:46,298 Starting quantification mode
2024-09-29 14:01:46,298 Collecting FASTQ files...
2024-09-29 14:01:46,298 SalmonTE assumes that '/media/leo/SSD500/Analysis_ASD/Control' is a directory, and SalmonTE will search any FASTQ file in the directory.
2024-09-29 14:01:46,300 The input dataset is considered as a single-end dataset.
2024-09-29 14:01:46,300 Collected 19 FASTQ files.
2024-09-29 14:01:46,300 Quantification has been finished.
2024-09-29 14:01:46,300 Running Salmon using Snakemake
Traceback (most recent call last):
  File "/home/leo/SalmonTE/./SalmonTE.py", line 295, in <module>
    run(args)
  File "/home/leo/SalmonTE/./SalmonTE.py", line 246, in run
    run_salmon(param)
  File "/home/leo/SalmonTE/./SalmonTE.py", line 144, in run_salmon
    snakemake.snakemake(
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'snakemake' has no attribute 'snakemake'

**Comment by edwardfu11** [comment]
Hello, I have the same issue when running SalmonTE.py.  Did you solve this issue yet?  Thanks in advance for your updates.

**Comment by janihuuh** [comment]
Running the same issue, any updates?
